# TP1

## Repositorios de información

## Ejercicio 1

- Descomprimir el archivo clima.tgz de la carpeta data
- Convertir cada archivo a Dataframe y mostrarlo en pantalla

In [ ]:
import pandas as pd
import tarfile
import os

path = "data/clima/"

objectoTar = tarfile.open("data/clima.tgz", "r")
objectoTar.extractall(f"{path}")
objectoTar.close()

files = os.listdir(f"{path}")
for name in files:
    df = pd.read_csv(f'{path}{name}', delimiter = "\t", header=[0,1], encoding='latin-1')
    print(name, "\n", df)
                
agosto08.txt 
      Unnamed: 0_level_0 Unnamed: 1_level_0 Temp.             Hum.  Pto.  \
                  Fecha               Hora  Ext.  Máx.  Mín. Ext. Rocío   
0              01/08/08               0:10  29.9  30.1  29.9   15   0.5   
1              01/08/08               0:20  29.7  29.9  29.7   17   2.1   
2              01/08/08               0:30  29.3  29.7  29.3   17   1.7   
3              01/08/08               0:40  29.1  29.3  29.1   18   2.3   
4              01/08/08               0:50  28.2  28.9  28.2   19   2.4   
...                 ...                ...   ...   ...   ...  ...   ...   
4459           31/08/08              23:20  23.9  24.1  23.9   38   8.8   
4460           31/08/08              23:30  23.9  23.9  23.9   38   8.8   
4461           31/08/08              23:40  23.9  23.9  23.9   38   8.8   
4462           31/08/08              23:50  23.9  23.9  23.9   38   8.8   
4463           01/09/08              00:00  23.8  23.9  23.8   38   8.7   

       Vel.   Dir.   Rec.  ... Hum. Rocío In.Cal. Unnamed: 31_level_0   Hum.  \
     Viento Viento Viento  ... Int.  Int.  Int.                  ET   Hoja 1   
0       0.9    WSW   0.54  ...   26   8.2    28.4                0.00    ---   
1       0.0    WSW   0.00  ...   26   8.2    28.4                0.00    ---   
2       0.0    WSW   0.00  ...   26   8.2    28.4                0.00    ---   
3       0.0    WSW   0.00  ...   26   8.2    28.4                0.00    ---   
4       0.0    WSW   0.00  ...   26   8.2    28.4                0.00    ---   
...     ...    ...    ...  ...  ...   ...     ...                 ...    ...   
4459    0.4     SW   0.27  ...   26  10.8    31.6                0.00    ---   
4460    0.9     SW   0.54  ...   26  10.7    31.5                0.00    ---   
4461    0.9     SW   0.54  ...   26  10.7    31.5                0.00    ---   
4462    0.9     SW   0.54  ...   26  10.7    31.5                0.00    ---   
4463    0.4     SW   0.27  ...   26  10.7    31.5                0.05    ---   

      Temp.  Muest   Tx   Recep. Int.  
     Hoja 1 Viento Viento   ISS  Arc.  
0       ---    186      1   81.6   10  
1       ---    234      1  100.0   10  
2       ---    235      1  100.0   10  
3       ---    234      1  100.0   10  
4       ---    233      1  100.0   10  
...     ...    ...    ...    ...  ...  
4459    ---    234      1  100.0   10  
4460    ---    235      1  100.0   10  
4461    ---    234      1  100.0   10  
4462    ---    234      1  100.0   10  
4463    ---    234      1  100.0   10  

[4464 rows x 38 columns]
agosto09.txt 
      Unnamed: 0_level_0 Unnamed: 1_level_0 Temp.             Hum.  Pto.  \
                  Fecha               Hora  Ext.  Máx.  Mín. Ext. Rocío   
0              01/08/09               0:10  30.4  30.6  30.4   15   0.8   
1              01/08/09               0:20  30.4  30.4  30.4   16   1.7   
2              01/08/09               0:30  30.1  30.4  30.1   17   2.3   
3              01/08/09               0:40  29.7  30.1  29.7   17   2.1   
4              01/08/09               0:50  29.5  29.7  29.5   17   1.9   
...                 ...                ...   ...   ...   ...  ...   ...   
4459           31/08/09              23:20  30.3  30.8  30.3   30  10.8   
4460           31/08/09              23:30  29.8  30.3  29.8   31  10.9   
4461           31/08/09              23:40  29.6  29.8  29.6   32  11.2   
4462           31/08/09              23:50  29.4  29.6  29.4   33  11.4   
4463           01/09/09              00:00  29.2  29.4  29.2   34  11.7   

       Vel.   Dir.   Rec.  ... Hum. Rocío In.Cal. Unnamed: 31_level_0   Hum.  \
     Viento Viento Viento  ... Int.  Int.  Int.                  ET   Hoja 1   
0       1.8    WSW   1.07  ...   13  -0.7    28.7                0.00    ---   
1       2.2    WSW   1.34  ...   13  -0.7    28.7                0.00    ---   
2       0.4      E   0.27  ...   13  -0.7    28.7                0.00    ---   
3       0.4    ENE   0.27  ...   13  -0.7    28.7                0.00    ---   
4       0.9    ENE   0.54  ...   13  -0.7    28.7                0.00    ---   
...     ...    ...    ...  ...  ...   ...     ...                 ...    ...   
4459    1.8      W   1.07  ...   22   9.3    32.4                0.00    ---   
4460    2.2    WSW   1.34  ...   22   9.3    32.4                0.00    ---   
4461    3.6    WSW   2.15  ...   22   9.3    32.4                0.00    ---   
4462    4.5    WSW   2.68  ...   22   9.3    32.4                0.00    ---   
4463    3.6      W   2.15  ...   22   9.3    32.4                0.15    ---   

      Temp.  Muest   Tx   Recep. Int.  
     Hoja 1 Viento Viento   ISS  Arc.  
0       ---    233      1  100.0   10  
1       ---    234      1  100.0   10  
2       ---    235      1  100.0   10  
3       ---    234      1  100.0   10  
4       ---    234      1  100.0   10  
...     ...    ...    ...    ...  ...  
4459    ---    235      1  100.0   10  
4460    ---    233      1  100.0   10  
4461    ---    234      1  100.0   10  
4462    ---    234      1  100.0   10  
4463    ---    234      1  100.0   10  

[4464 rows x 38 columns]
agosto10.txt 
      Unnamed: 0_level_0 Unnamed: 1_level_0 Temp.             Hum.  Pto.  \
                  Fecha               Hora  Ext.  Máx.  Mín. Ext. Rocío   
0              01/08/10               0:10  30.7  30.9  30.7   24   7.8   
1              01/08/10               0:20  30.4  30.7  30.4   25   8.1   
2              01/08/10               0:30  30.1  30.4  30.1   25   7.9   
3              01/08/10               0:40  29.7  30.1  29.7   26   8.2   
4              01/08/10               0:50  29.3  29.7  29.3   27   8.3   
...                 ...                ...   ...   ...   ...  ...   ...   
4459           31/08/10              23:20  29.6  29.6  29.6   39  14.2   
4460           31/08/10              23:30  29.4  29.6  29.4   40  14.4   
4461           31/08/10              23:40  29.2  29.4  29.2   40  14.2   
4462           31/08/10              23:50  29.1  29.2  29.1   41  14.5   
4463           01/09/10              00:00  28.9  29.1  28.9   41  14.4   

       Vel.   Dir.   Rec.  ... Grad.D. Temp. Hum. Rocío In.Cal.  \
     Viento Viento Viento  ...   Frío   Int. Int.  Int.  Int.     
0       0.9      E   0.54  ...   0.086  34.6   23  10.5    33.3   
1       0.4      E   0.27  ...   0.084  34.5   23  10.4    33.2   
2       0.4      E   0.27  ...   0.081  34.5   23  10.4    33.2   
3       0.4      E   0.27  ...   0.079  34.5   23  10.4    33.2   
4       0.0      E   0.00  ...   0.076  34.5   23  10.4    33.2   
...     ...    ...    ...  ...     ...   ...  ...   ...     ...   
4459    0.9    SSE   0.54  ...   0.078  35.4   24  11.7    34.6   
4460    0.9    ENE   0.54  ...   0.077  35.4   24  11.7    34.6   
4461    1.8    ENE   1.07  ...   0.075  35.4   24  11.7    34.6   
4462    0.9    ENE   0.54  ...   0.074  35.4   24  11.7    34.6   
4463    0.9    ENE   0.54  ...   0.074  35.4   24  11.7    34.6   

     Unnamed: 31_level_0  Muest   Tx   Recep. Int.  
                    ET   Viento Viento   ISS  Arc.  
0                   0.00    231      1  100.0   10  
1                   0.00    234      1  100.0   10  
2                   0.00    235      1  100.0   10  
3                   0.00    234      1  100.0   10  
4                   0.00    234      1  100.0   10  
...                  ...    ...    ...    ...  ...  
4459                0.00    232      1  100.0   10  
4460                0.00    232      1  100.0   10  
4461                0.00    235      1  100.0   10  
4462                0.00    234      1  100.0   10  
4463                0.05    232      1  100.0   10  

[4464 rows x 36 columns]
agosto12.txt 
      Unnamed: 0_level_0 Unnamed: 1_level_0 Temp.             Hum.  Pto.  \
                  Fecha               Hora  Ext.  Máx.  Mín. Ext. Rocío   
0              01/08/12               0:10  31.7  32.2  31.7   18   4.5   
1              01/08/12               0:20  31.2  31.7  31.2   19   4.8   
2              01/08/12               0:30  30.6  31.2  30.6   19   4.4   
3              01/08/12               0:40  30.4  30.6  30.4   19   4.2   
4              01/08/12               0:50  29.8  30.4  29.8   20   4.4   
...                 ...                ...   ...   ...   ...  ...   ...   
4459           31/08/12              23:20  26.7  27.0  26.7   18   0.4   
4460           31/08/12              23:30  26.4  26.7  26.4   18   0.1   
4461           31/08/12              23:40  26.1  26.4  26.1   18  -0.1   
4462           31/08/12              23:50  25.9  26.1  25.9   18  -0.3   
4463           01/09/12              00:00  25.7  25.9  25.7   17  -1.2   

       Vel.   Dir.   Rec.  ... Grad.D. Temp. Hum. Rocío In.Cal.  \
     Viento Viento Viento  ...   Frío   Int. Int.  Int.  Int.     
0       0.4     SW   0.27  ...   0.093  32.3   22   7.8    30.6   
1       0.0    ---   0.00  ...   0.089  32.3   22   7.8    30.6   
2       0.4    SSE   0.27  ...   0.085  32.3   22   7.8    30.6   
3       1.3    ESE   0.80  ...   0.084  32.3   22   7.8    30.6   
4       0.0    ESE   0.00  ...   0.079  32.3   22   7.8    30.6   
...     ...    ...    ...  ...     ...   ...  ...   ...     ...   
4459    0.9     NW   0.54  ...   0.058  33.1   22   8.5    31.4   
4460    0.4     NW   0.27  ...   0.056  33.1   22   8.5    31.4   
4461    0.4     NW   0.27  ...   0.054  33.1   22   8.5    31.4   
4462    0.4     NW   0.27  ...   0.052  33.1   22   8.5    31.4   
4463    0.4     NW   0.27  ...   0.051  33.1   22   8.5    31.4   

     Unnamed: 31_level_0  Muest   Tx   Recep. Int.  
                    ET   Viento Viento   ISS  Arc.  
0                   0.00    227      2  100.0   10  
1                   0.00    229      2  100.0   10  
2                   0.00    227      2  100.0   10  
3                   0.00    229      2  100.0   10  
4                   0.00    229      2  100.0   10  
...                  ...    ...    ...    ...  ...  
4459                0.00    177      2   79.7   10  
4460                0.00    156      2   70.3   10  
4461                0.00    151      2   68.0   10  
4462                0.00    150      2   67.6   10  
4463                0.05    155      2   69.8   10  

[4464 rows x 36 columns]
agosto11.txt 
      Unnamed: 0_level_0 Unnamed: 1_level_0 Temp.             Hum.  Pto.  \
                  Fecha               Hora  Ext.  Máx.  Mín. Ext. Rocío   
0              01/08/11               0:10  27.6  27.6  27.6   24   5.2   
1              01/08/11               0:20  27.6  27.6  27.6   24   5.2   
2              01/08/11               0:30  27.1  27.6  27.1   25   5.4   
3              01/08/11               0:40  26.7  27.1  26.7   25   5.0   
4              01/08/11               0:50  26.9  26.9  26.7   25   5.2   
...                 ...                ...   ...   ...   ...  ...   ...   
4459           31/08/11              23:20  22.7  22.7  22.7   64  15.5   
4460           31/08/11              23:30  22.6  22.7  22.6   64  15.4   
4461           31/08/11              23:40  22.4  22.6  22.4   64  15.3   
4462           31/08/11              23:50  22.3  22.4  22.3   64  15.1   
4463           01/09/11              00:00  22.1  22.3  22.1   65  15.2   

       Vel.   Dir.   Rec.  ... Grad.D. Temp. Hum. Rocío In.Cal.  \
     Viento Viento Viento  ...   Frío   Int. Int.  Int.  Int.     
0       0.0      S   0.00  ...   0.064  30.9   23   7.4    29.2   
1       0.0      S   0.00  ...   0.064  30.9   23   7.4    29.2   
2       0.0      S   0.00  ...   0.061  30.9   23   7.4    29.2   
3       0.0    ---   0.00  ...   0.058  30.9   23   7.4    29.2   
4       0.0    ---   0.00  ...   0.059  30.9   23   7.4    29.2   
...     ...    ...    ...  ...     ...   ...  ...   ...     ...   
4459    3.1      W   1.88  ...   0.030  26.9   22   3.4    25.3   
4460    3.1      W   1.88  ...   0.029  26.8   22   3.3    25.3   
4461    3.6    WSW   2.15  ...   0.029  26.8   22   3.3    25.3   
4462    3.6      W   2.15  ...   0.027  26.8   22   3.3    25.3   
4463    3.1      W   1.88  ...   0.026  26.7   22   3.2    25.2   

     Unnamed: 31_level_0  Muest   Tx   Recep. Int.  
                    ET   Viento Viento   ISS  Arc.  
0                   0.00    228      2  100.0   10  
1                   0.00    229      2  100.0   10  
2                   0.00    229      2  100.0   10  
3                   0.00    228      2  100.0   10  
4                   0.00    228      2  100.0   10  
...                  ...    ...    ...    ...  ...  
4459                0.00    228      2  100.0   10  
4460                0.00    227      2  100.0   10  
4461                0.00    229      2  100.0   10  
4462                0.00    214      2   96.4   10  
4463                0.08    229      2  100.0   10  

[4464 rows x 36 columns]

## Ejercicio 2

- Obtener de la API de <a href="https://wikimedia.org/api/rest_v1/#/Pageviews%20data">Wikimedia </a> la cantidad de visitas en este año a la página Albert Einstein por día.
- Mostrar el Dataframe obtenido por pantalla

In [ ]:
import requests
import pandas as pd
url = "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/es.wikipedia.org/all-access/all-agents/Albert_Einstein/daily/20210101/20211230"
r = requests.get(url, headers={'user-agent':'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:91.0) Gecko/20100101 Firefox/91.0'})
data = r.json()
df = pd.DataFrame(data["items"])
df
project	article	granularity	timestamp	access	agent	views
0	es.wikipedia	Albert_Einstein	daily	2021010100	all-access	all-agents	2345
1	es.wikipedia	Albert_Einstein	daily	2021010200	all-access	all-agents	2928
2	es.wikipedia	Albert_Einstein	daily	2021010300	all-access	all-agents	3513
3	es.wikipedia	Albert_Einstein	daily	2021010400	all-access	all-agents	3756
4	es.wikipedia	Albert_Einstein	daily	2021010500	all-access	all-agents	3304
...	...	...	...	...	...	...	...
235	es.wikipedia	Albert_Einstein	daily	2021082400	all-access	all-agents	4228
236	es.wikipedia	Albert_Einstein	daily	2021082500	all-access	all-agents	4460
237	es.wikipedia	Albert_Einstein	daily	2021082600	all-access	all-agents	4551
238	es.wikipedia	Albert_Einstein	daily	2021082700	all-access	all-agents	4031
239	es.wikipedia	Albert_Einstein	daily	2021082800	all-access	all-agents	3369
240 rows × 7 columns

## Ejercicio 3

- Crear una base de datos MySQL
- Crear una tabla que contenga nombre, apellido y teléfono
- Obtener de la base de datos la lista de personas ordenada por apellido de forma descendente
- Mostrar el Dataframe resultante por pantalla

In [ ]:
import mysql.connector as connection
import pandas as pd

db = connection.connect(host="localhost", database = "clientes",user="root", passwd="danilo",use_pure=True)

query = "SELECT * from Clientes"
df = pd.read_sql(query,db)
db.close()
df
Id	Nombre	Apellido
0	1	Gabriel  Lopez
1	2	Javier	 Martinez
2	3	Pablo	 Sanz

## Ejercicio 4

- Obtener de la API <a href="https://date.nager.at/swagger/index.html">Nager.Date</a> las fiestas nacionales argentinas para el 2021
- Mostrar el dataframe resultante por pantalla

In [ ]:
import requests
import pandas as pd
url = "https://date.nager.at/api/v1/Get/AR/2021"
r = requests.get(url, headers={'user-agent':'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:91.0) Gecko/20100101 Firefox/91.0'})
data = r.json()
df = pd.DataFrame(data)
df
date	localName	name	countryCode	fixed	global	counties	launchYear	type
0	2021-01-01	Año Nuevo	New Year's Day	AR	True	True	None	NaN	Public
1	2021-02-15	Carnaval	Carnival	AR	False	True	None	NaN	Public
2	2021-02-16	Carnaval	Carnival	AR	False	True	None	NaN	Public
3	2021-03-24	Día Nacional de la Memoria por la Verdad y la ...	Day of Remembrance for Truth and Justice	AR	True	True	None	NaN	Public
4	2021-04-02	Día del Veterano y de los Caídos en la Guerra ...	Day of the Veterans and Fallen of the Malvinas...	AR	True	True	None	NaN	Public
5	2021-04-02	Viernes Santo	Good Friday	AR	False	True	None	NaN	Public
6	2021-05-01	Día del Trabajador	Labour Day	AR	True	True	None	NaN	Public
7	2021-05-25	Día de la Revolución de Mayo	May Revolution	AR	True	True	None	NaN	Public
8	2021-06-17	Paso a la Inmortalidad del General Martín Migu...	Anniversary of the Passing of General Martín M...	AR	True	True	None	2016.0	Public
9	2021-06-20	Paso a la Inmortalidad del General Manuel Belg...	General Manuel Belgrano Memorial Day	AR	True	True	None	NaN	Public
10	2021-07-09	Día de la Independencia	Independence Day	AR	True	True	None	NaN	Public
11	2021-08-16	Paso a la Inmortalidad del General José de San...	General José de San Martín Memorial Day	AR	False	True	None	NaN	Public
12	2021-10-11	Día del Respeto a la Diversidad Cultural	Day of Respect for Cultural Diversity	AR	False	True	None	NaN	Public
13	2021-11-20	Día de la Soberanía Nacional	National Sovereignty Day	AR	True	True	None	NaN	Public
14	2021-12-08	Día de la Inmaculada Concepción de María	Immaculate Conception Day	AR	True	True	None	NaN	Public
15	2021-12-25	Navidad	Christmas Day	AR	True	True	None	NaN	Public

## Ejercicio 5

- Obtener una tabla informativa de una página a elección con Web Scrapping
- Mostrar el Dataframe resultante por pantalla

In [ ]:
import requests
import pandas as pd
url = 'https://www.promiedos.com.ar/primera'
table = pd.read_html(url, header=0, index_col=0)
table[0]
Equipo	Pts	PJ	PG	PE	PP	GF	GC	DIF
#									
1	Lanus	19	9	6	1	2	19	15	4
2	Independiente	18	9	5	3	1	10	4	6
3	Estudiantes (LP)	16	8	5	1	2	15	7	8
4	Racing Club	16	9	4	4	1	8	1	7
5	Talleres (C)	16	8	5	1	2	12	7	5
6	River Plate	14	8	4	2	2	15	6	9
7	Colon	14	9	4	2	3	8	13	-5
8	Aldosivi	13	9	4	1	4	11	12	-1
9	Def y Justicia	12	9	3	3	3	11	9	2
10	Patronato	12	8	3	3	2	8	6	2
11	Argentinos	12	8	3	3	2	7	5	2
12	Boca Juniors	11	9	2	5	2	6	6	0
13	Newells	11	8	3	2	3	9	10	-1
14	Atl Tucuman	11	8	3	2	3	9	11	-2
15	Velez	10	9	2	4	3	9	6	3
16	Rosario Central	10	9	3	1	5	13	11	2
17	Gimnasia (LP)	10	9	2	4	3	7	9	-2
18	Sarmiento (J)	10	8	3	1	4	8	11	-3
19	Godoy Cruz	10	9	3	1	5	10	15	-5
20	Union	9	8	2	3	3	9	10	-1
21	Huracan	9	9	1	6	2	6	7	-1
22	Platense	9	9	2	3	4	12	14	-2
23	Banfield	8	9	1	5	3	7	11	-4
24	San Lorenzo	8	8	2	2	4	5	11	-6
25	Central Cba (SdE)	7	9	1	4	4	9	13	-4
26	Arsenal	6	9	1	3	5	5	18	-13